## This CI script builds CAER with all default modules on UBUNTU 16.04.
# all dependencies are the versions of the Ubuntu 16.04 LTS repo except opencv

language: cpp

sudo: required
dist: trusty # newest ubuntu version in TRAVIS-CI (will be partly upgraded)

#install all required packages from ubuntu 16.04!
before_install:
  - sudo add-apt-repository 'deb http://ch.archive.ubuntu.com/ubuntu xenial main universe' -y
  - sudo apt-get update -q
  #install requirements for libcaer and caer
  - sudo apt-get install unzip libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-system-dev
    libmxml-dev libusb-1.0-0-dev liballegro5-dev libtcmalloc-minimal4 -y -q
  # install libuv version 1.X which is not available in ubuntu 14.04
  - sudo apt-get install g++/xenial -y -q
  - sudo apt-get install libuv1/xenial -y -q
  - sudo apt-get install libuv1-dev/xenial -y -q

# the stages are used to ensure that, in case of a failed build, the failure is detected early and the other long builds
# are not run.
# the setup time for a non opencv build is ca 3min in travis-ci
# (because caer needs ubuntu 16.04 packages a lot of packages have to be installed)
# the setup time for a OpenCV build is ca 28min in travis-ci
# (because of lack of precompiled packages opencv has to be compiled before the build ca 25min)

jobs:
  include:
    - stage: build plain
      before_script:
        # install latest libcaer release
        - wget -q --output-document=libcaer.zip https://api.github.com/repos/inilabs/libcaer/zipball
        - unzip -q libcaer.zip
        - rm libcaer.zip
        - mv inilabs-l* libcaer
        - cd libcaer
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_OPENCV=0 .
        - make -s clean
        - make -s
        - sudo make -s install
        - cd ..
      script:
        # build with all default modules
        - cmake .
        - make clean
        - make
        - ctest
    - stage: build modules
      before_script:
        # install latest libcaer release
        - wget -q --output-document=libcaer.zip https://api.github.com/repos/inilabs/libcaer/zipball
        - unzip -q libcaer.zip
        - rm libcaer.zip
        - mv inilabs-l* libcaer
        - cd libcaer
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_OPENCV=0 .
        - make -s clean
        - make -s
        - sudo make -s install
        - cd ..
      script:
        # build with all default modules without opencv
        - cmake -DDVS128=1 -DEDVS=1 -DDAVIS=1 -DDYNAPSE=1 -DBAFILTER=1 -DFRAMEENHANCER=1 -DCAMERACALIBRATION=0
          -DPOSEESTIMATION=0 -DSTATISTICS=1 -DVISUALIZER=1 -DINPUT_FILE=1 -DOUTPUT_FILE=1 -DINPUT_NETWORK=1
          -DOUTPUT_NETWORK=1 -DROTATE=1 -DMEDIANTRACKER=1 -DRECTANGULARTRACKER=1 -DDYNAMICRECTANGULARTRACKER=1
          -DSPIKEFEATURES=1 -DMEANRATEFILTER=1 -DSYNAPSERECONFIG=1 -DFPGASPIKEGEN=1 -DPOISSONSPIKEGEN=1 .
        - make clean
        - make
        - ctest
    - stage: build modules with OpenCV # with opencv takes a long time!
      before_script:
        # install opencv 3.1 +contrib
        - wget -q --output-document=opencv.zip https://github.com/opencv/opencv/archive/3.1.0.zip
        - unzip -q opencv.zip
        - cd opencv-3.1.0
        - wget -q --output-document=opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/3.1.0.zip
        - unzip -q opencv_contrib.zip
        - mkdir build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_IPP=ON -DINSTALL_CREATE_DISTRIB=ON
          -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-3.1.0/modules/ -DBUILD_opencv_contrib_world=OFF
          -DBUILD_opencv_xfeatures2d=OFF -DBUILD_opencv_matlab=OFF -DBUILD_opencv_text=OFF -DBUILD_opencv_xobjdetect=OFF -DBUILD_opencv_aruco=ON ../
        - make -s
        - sudo make -s install
        - cd ../..
        # install latest libcaer release
        - wget -q --output-document=libcaer.zip https://api.github.com/repos/inilabs/libcaer/zipball
        - unzip -q libcaer.zip
        - rm libcaer.zip
        - mv inilabs-l* libcaer
        - cd libcaer
        - cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_OPENCV=1 .
        - make -s clean
        - make -s
        - sudo make -s install
        - cd ..
      script:
        # build with all default modules incl opencv
        - cmake -DDVS128=1 -DEDVS=1 -DDAVIS=1 -DDYNAPSE=1 -DBAFILTER=1 -DFRAMEENHANCER=1 -DCAMERACALIBRATION=1
          -DPOSEESTIMATION=1 -DSTATISTICS=1 -DVISUALIZER=1 -DINPUT_FILE=1 -DOUTPUT_FILE=1 -DINPUT_NETWORK=1
          -DOUTPUT_NETWORK=1 -DROTATE=1 -DMEDIANTRACKER=1 -DRECTANGULARTRACKER=1 -DDYNAMICRECTANGULARTRACKER=1
          -DSPIKEFEATURES=1 -DMEANRATEFILTER=1 -DSYNAPSERECONFIG=1 -DFPGASPIKEGEN=1 -DPOISSONSPIKEGEN=1 .
        - make clean
        - make